version: "2"

services:
  apollo:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - "./:/server"
    command: "npm start"
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
